'Makefile' modified to support creation of .msi leveraging te rundeck-launcher. 'rundeck.wxs' modified to support streamlined instalation.

diff --git a/packaging/Makefile b/packaging/Makefile
--- a/packaging/Makefile
+++ b/packaging/Makefile
@@ -29,10 +29,12 @@ endif
 rpm: dist
 	rpmbuild -bb --target=noarch-linux $(RPMBUILD_DEFINES) --buildroot ${PWD}/dist/SOURCES rundeck.spec 
 
-msi: dist
+checkwix:
 	@if ! which candle.exe >&/dev/null; then \
-	   echo 'ERROR: Please put WIX-35 tools in your path.'; exit 1; \
+          echo 'ERROR: Please put WIX-35 tools in your path.'; exit 1; \
 	 fi
+
+msi: checkwix msidist dist/SOURCES/stacktrace.log
 	cp LICENSE.rtf dist/SOURCES ;\
 	cd dist/SOURCES ;\
 	heat.exe dir "." -nologo \
@@ -53,6 +55,39 @@ msi: dist
 	  -ext WixUIExtension -cultures:en-us \
 	  ../rundeck.wixobj ../FileFragment.wixobj
 
+msidist:
+	@mkdir -p dist/SOURCES
+	@cp ../rundeckapp/target/rundeck-launcher-*.jar dist/SOURCES
+
+dist/SOURCES/stacktrace.log:
+	@ while [ ! -f dist/SOURCES/stacktrace.log ] ; do \
+	echo "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *"; \
+	echo "* In another window, please invoke the launcher using:      *"; \
+	echo "*                                                           *"; \
+	echo "*    # cd dist/SOURCES; java -jar rundeck-launcher-*.jar    *"; \
+	echo "*                                                           *"; \
+	echo "* Once the launcher is listening on HTTP port, press CTRL+C *"; \
+	echo "* and press any key in this window to continue . . .        *"; \
+	echo "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *"; \
+	read -n1 -s ;\
+	done
+	@rm -f dist/SOURCES/server/config/jaas-loginmodule.conf
+	@rm -f dist/SOURCES/server/config/realm.properties
+	@rm -f dist/SOURCES/server/config/rundeck-config.properties
+	@rm -f dist/SOURCES/server/config/ssl.properties
+	@rm -f dist/SOURCES/server/exp/webapp/WEB-INF/classes/log4j.properties
+	@rm -f dist/SOURCES/etc/admin.aclpolicy
+	@rm -f dist/SOURCES/etc/console-log4j.properties
+	@rm -f dist/SOURCES/etc/framework.properties
+	@rm -f dist/SOURCES/etc/log4j.properties
+	@rm -f dist/SOURCES/etc/preferences.properties
+	@rm -f dist/SOURCES/etc/profile
+	@rm -f dist/SOURCES/etc/profile.bat
+	@rm -f dist/SOURCES/etc/project.properties
+	@touch dist/SOURCES/server/exp/webapp/WEB-INF/classes/log4j.properties
+	@find  dist/SOURCES -type f ! -path \*/server/data/\* \
+	 | xargs -n 40 truncate --size=0
+
 dist:
 	@mkdir -p dist/RPMS/noarch
 	@mkdir -p dist/SOURCES
@@ -66,10 +101,10 @@ dist:
 	@mkdir -p dist/SOURCES/usr/share/man/man{1,5}
 	@mkdir -p dist/SOURCES/usr/share/man/en/man{1,5}
 	@cp -R root/* dist/SOURCES
-	@-cp ../docs/en/manpages/man1/*.1.gz dist/SOURCES/usr/share/man/man1
-	@-cp ../docs/en/manpages/man5/*.5.gz dist/SOURCES/usr/share/man/man5
-	@-cp ../docs/en/manpages/man1/*.1.gz dist/SOURCES/usr/share/man/en/man1
-	@-cp ../docs/en/manpages/man5/*.5.gz dist/SOURCES/usr/share/man/en/man5
+	@cp ../docs/en/manpages/man1/*.1.gz dist/SOURCES/usr/share/man/man1
+	@cp ../docs/en/manpages/man5/*.5.gz dist/SOURCES/usr/share/man/man5
+	@cp ../docs/en/manpages/man1/*.1.gz dist/SOURCES/usr/share/man/en/man1
+	@cp ../docs/en/manpages/man5/*.5.gz dist/SOURCES/usr/share/man/en/man5
 	@cp -R ../core/build/tools/lib/*.jar dist/SOURCES/var/lib/rundeck/cli
 	@cp ../core/build/libs/rundeck-core-*.jar dist/SOURCES/var/lib/rundeck/cli
 	@cp ../rundeckapp/target/rundeck-server-*.jar dist/SOURCES/var/lib/rundeck/bootstrap	
